# RDD Social Media
### Muhammad Naufal Satriandana 13520068

## Initial Setup

In [1]:
import datetime
import time

url = "hdfs://127.0.0.1:9000/socmed_input_alt/"
out_url = "hdfs://127.0.0.1:9000/socmed_output_alt/"
spark

## Instagram

In [2]:
ig = spark.read.json(f"{url}instagram*.json").rdd
# map the lines to a key-value pair
def map(line):
    date = line['created_time']
    # format date
    date = datetime.datetime.fromtimestamp(int(date)).strftime('%Y-%m-%d')
    return (("instagram", date), 1)

ig = ig.map(map)

ig = ig.reduceByKey(lambda x, y: x + y)

ig = ig.map(lambda x: (x[0][0], x[0][1], x[1]))

ig.take(5)

[('instagram', '2022-01-12', 439),
 ('instagram', '2022-01-26', 1235),
 ('instagram', '2022-01-19', 1357),
 ('instagram', '2022-01-04', 446),
 ('instagram', '2021-11-20', 150)]

## Youtube

In [3]:
yt = spark.read.json(f"{url}youtube*.json").rdd
# map the lines to a key-value pair
def map(line):
    snippet = line['snippet']
    # check if comment is a reply
    if snippet['topLevelComment'] is not None:
        snippet = snippet['topLevelComment']['snippet']
    # get date from snippet.publishedAt
    date = snippet['publishedAt'][0:10]
    return (("youtube", date), 1)

yt = yt.map(map)

yt = yt.reduceByKey(lambda x, y: x + y)

yt = yt.map(lambda x: (x[0][0], x[0][1], x[1]))

yt.take(5)

[('youtube', '2021-10-11', 41),
 ('youtube', '2021-04-14', 68),
 ('youtube', '2021-05-23', 16),
 ('youtube', '2021-04-16', 22),
 ('youtube', '2021-04-17', 16)]

## Twitter

In [4]:
twt = spark.read.json(f"{url}twitter*.json").rdd
# map the lines to a key-value pair
def map(line):
    date = line['created_at']
    # format date
    date = datetime.datetime.strptime(date, '%a %b %d %H:%M:%S %z %Y').strftime('%Y-%m-%d')
    return (("twitter", date), 1)

twt = twt.map(map)

twt = twt.reduceByKey(lambda x, y: x + y)

twt = twt.map(lambda x: (x[0][0], x[0][1], x[1]))

twt.take(5)

[('twitter', '2021-12-23', 51),
 ('twitter', '2021-12-22', 208),
 ('twitter', '2022-01-26', 593),
 ('twitter', '2021-12-29', 209),
 ('twitter', '2021-12-31', 77)]

## Facebook

In [5]:
fb = spark.read.json(f"{url}facebook*.json").rdd

def map(line):
    result = []
    postDate = line["created_time"][0:10]
    comments = line["comments"]["data"]
    result.append((("facebook", postDate), 1))
    for comment in comments:
        date = comment["created_time"][0:10]
        result.append((("facebook", date), 1))
    return result

fb = fb.flatMap(map)

fb = fb.reduceByKey(lambda x, y: x + y)

fb = fb.map(lambda x: (x[0][0], x[0][1], x[1]))
fb.take(5)

[('facebook', '2022-01-01', 125),
 ('facebook', '2021-12-08', 209),
 ('facebook', '2021-12-05', 32),
 ('facebook', '2021-11-24', 27),
 ('facebook', '2021-11-22', 28)]

## Others

In [6]:
others = spark.read.option("multiline","true").json(f"{url}*.json.json").rdd
# map the lines to a key-value pair
def map(line):
    graphImages = line['GraphImages']
    result = []
    if(graphImages is not None):
        for image in graphImages:
            if image['taken_at_timestamp'] is not None:
                date = datetime.datetime.fromtimestamp(image['taken_at_timestamp']).strftime('%Y-%m-%d')
                result.append((("instagram", date), 1))
            if image['comments'] is not None:
                comments = image['comments']['data']
                for comment in comments:
                    date = datetime.datetime.fromtimestamp(comment['created_at']).strftime('%Y-%m-%d')
                    result.append((("instagram", date), 1))
    return result

others = others.flatMap(map)

others = others.reduceByKey(lambda x, y: x + y)

others = others.map(lambda x: (x[0][0], x[0][1], x[1]))

others.take(5)

[(('instagram', '2022-02-12'), 572),
 (('instagram', '2022-02-05'), 68),
 (('instagram', '2022-01-09'), 13),
 (('instagram', '2022-01-07'), 13),
 (('instagram', '2021-12-01'), 1)]

## Combined

In [12]:
RDD = others.union(ig.union(yt.union(twt.union(fb))))
RDD.collect()

[(('instagram', '2022-02-12'), 572),
 (('instagram', '2022-02-05'), 68),
 (('instagram', '2022-01-09'), 13),
 (('instagram', '2022-01-07'), 13),
 (('instagram', '2021-12-01'), 1),
 (('instagram', '2021-11-20'), 3),
 (('instagram', '2021-11-06'), 2),
 (('instagram', '2021-10-15'), 1),
 (('instagram', '2021-09-18'), 1),
 (('instagram', '2021-09-15'), 1),
 (('instagram', '2021-09-10'), 2),
 (('instagram', '2022-02-10'), 529),
 (('instagram', '2022-02-07'), 478),
 (('instagram', '2022-02-06'), 211),
 (('instagram', '2022-01-27'), 8),
 (('instagram', '2022-01-26'), 7),
 (('instagram', '2022-01-22'), 24),
 (('instagram', '2022-02-02'), 1),
 (('instagram', '2022-01-20'), 12),
 (('instagram', '2022-01-14'), 11),
 (('instagram', '2022-01-06'), 40),
 (('instagram', '2022-01-03'), 8),
 (('instagram', '2021-12-31'), 7),
 (('instagram', '2021-12-30'), 21),
 (('instagram', '2021-12-27'), 2),
 (('instagram', '2021-12-06'), 1),
 (('instagram', '2021-11-30'), 1),
 (('instagram', '2021-11-11'), 3),
 (('instagram', '2021-09-22'), 1),
 (('instagram', '2021-09-14'), 2),
 (('instagram', '2021-09-08'), 1),
 (('instagram', '2022-02-14'), 310),
 (('instagram', '2022-02-11'), 817),
 (('instagram', '2022-02-08'), 435),
 (('instagram', '2022-02-04'), 83),
 (('instagram', '2022-01-25'), 11),
 (('instagram', '2022-01-23'), 7),
 (('instagram', '2022-01-24'), 8),
 (('instagram', '2022-01-12'), 9),
 (('instagram', '2022-01-02'), 8),
 (('instagram', '2022-01-05'), 6),
 (('instagram', '2021-11-07'), 3),
 (('instagram', '2022-02-15'), 208),
 (('instagram', '2022-02-13'), 404),
 (('instagram', '2022-02-03'), 28),
 (('instagram', '2022-01-30'), 9),
 (('instagram', '2022-01-28'), 2),
 (('instagram', '2022-01-31'), 4),
 (('instagram', '2022-01-29'), 1),
 (('instagram', '2022-01-17'), 8),
 (('instagram', '2022-01-16'), 7),
 (('instagram', '2022-01-15'), 16),
 (('instagram', '2022-01-08'), 17),
 (('instagram', '2022-01-10'), 12),
 (('instagram', '2022-01-11'), 6),
 (('instagram', '2022-01-01'), 14),
 (('instagram', '2021-12-28'), 2),
 (('instagram', '2021-12-14'), 1),
 (('instagram', '2021-12-09'), 2),
 (('instagram', '2021-12-02'), 2),
 (('instagram', '2021-11-15'), 1),
 (('instagram', '2021-11-13'), 1),
 (('instagram', '2021-11-08'), 10),
 (('instagram', '2021-11-04'), 1),
 (('instagram', '2021-11-01'), 1),
 (('instagram', '2021-10-16'), 1),
 (('instagram', '2021-10-11'), 1),
 (('instagram', '2021-10-10'), 1),
 (('instagram', '2021-09-16'), 2),
 (('instagram', '2021-09-07'), 2),
 (('instagram', '2022-02-09'), 423),
 (('instagram', '2022-02-01'), 6),
 (('instagram', '2022-01-21'), 16),
 (('instagram', '2022-01-19'), 15),
 (('instagram', '2022-01-13'), 14),
 (('instagram', '2022-01-18'), 7),
 (('instagram', '2022-01-04'), 4),
 (('instagram', '2021-11-21'), 2),
 (('instagram', '2021-11-18'), 1),
 (('instagram', '2021-11-12'), 6),
 (('instagram', '2021-10-13'), 2),
 (('instagram', '2021-10-12'), 1),
 (('instagram', '2021-10-06'), 3),
 (('instagram', '2021-09-12'), 1),
 ('instagram', '2022-01-12', 439),
 ('instagram', '2022-01-26', 1235),
 ('instagram', '2022-01-19', 1357),
 ('instagram', '2022-01-04', 446),
 ('instagram', '2021-11-20', 150),
 ('instagram', '2021-11-12', 148),
 ('instagram', '2021-11-09', 65),
 ('instagram', '2021-11-03', 96),
 ('instagram', '2021-10-26', 44),
 ('instagram', '2021-10-19', 65),
 ('instagram', '2021-10-07', 38),
 ('instagram', '2021-08-05', 6),
 ('instagram', '2021-07-16', 110),
 ('instagram', '2021-06-24', 13),
 ('instagram', '2021-07-13', 10),
 ('instagram', '2021-04-11', 9),
 ('instagram', '2021-02-24', 21),
 ('instagram', '2021-02-18', 17),
 ('instagram', '2021-07-30', 14),
 ('instagram', '2021-08-20', 4),
 ('instagram', '2022-02-02', 2125),
 ('instagram', '2022-02-13', 1029),
 ('instagram', '2022-01-28', 1347),
 ('instagram', '2022-01-03', 378),
 ('instagram', '2021-11-29', 136),
 ('instagram', '2021-10-04', 50),
 ('instagram', '2021-09-25', 50),
 ('instagram', '2021-09-12', 28),
 ('instagram', '2021-07-11', 14),
 ('instagram', '2021-06-17', 21),
 ('instagram', '2021-05-22', 32),
 ('instagram', '2021-03-28', 10),
 ('instagram', '2021-06-05', 8),
 ('instagram', '2021-05-25', 18),
 ('instagram', '2021-04-25', 35),
 ('instagram', '2021-02-23', 11),
 ('instagram', '2021-04-14', 5),
 ('instagram', '2021-08-10', 9),
 ('instagram', '2021-08-17', 20),
 ('instagram', '2021-01-12', 3),
 ('instagram', '2022-02-05', 1823),
 ('instagram', '2022-02-03', 2375),
 ('instagram', '2022-01-21', 1313),
 ('instagram', '2021-12-29', 40),
 ('instagram', '2021-12-23', 37),
 ('instagram', '2021-12-18', 54),
 ('instagram', '2021-11-30', 81),
 ('instagram', '2021-10-27', 106),
 ('instagram', '2021-10-16', 54),
 ('instagram', '2021-10-10', 39),
 ('instagram', '2021-10-09', 75),
 ('instagram', '2021-09-16', 66),
 ('instagram', '2021-09-10', 58),
 ('instagram', '2021-07-15', 98),
 ('instagram', '2021-07-09', 10),
 ('instagram', '2021-06-18', 2),
 ('instagram', '2021-06-11', 20),
 ('instagram', '2021-06-10', 14),
 ('instagram', '2021-07-02', 17),
 ('instagram', '2021-04-29', 74),
 ('instagram', '2021-05-26', 6),
 ('instagram', '2021-02-01', 16),
 ('instagram', '2021-02-19', 12),
 ('instagram', '2021-01-11', 5),
 ('instagram', '2020-12-22', 3),
 ('instagram', '2022-02-15', 542),
 ('instagram', '2022-02-14', 1345),
 ('instagram', '2022-01-05', 525),
 ('instagram', '2021-09-24', 56),
 ('instagram', '2021-11-15', 113),
 ('instagram', '2021-11-04', 78),
 ('instagram', '2021-10-28', 106),
 ('instagram', '2021-07-24', 15),
 ('instagram', '2021-06-30', 162),
 ('instagram', '2021-06-28', 136),
 ('instagram', '2021-06-27', 10),
 ('instagram', '2021-06-23', 23),
 ('instagram', '2021-06-22', 12),
 ('instagram', '2021-05-23', 3),
 ('instagram', '2021-05-18', 16),
 ('instagram', '2021-04-10', 4),
 ('instagram', '2021-01-09', 3),
 ('instagram', '2021-02-14', 95),
 ('instagram', '2021-02-15', 18),
 ('instagram', '2021-05-03', 22),
 ('instagram', '2021-04-26', 22),
 ('instagram', '2021-06-07', 10),
 ('instagram', '2021-03-04', 14),
 ('instagram', '2021-08-23', 12),
 ('instagram', '2021-12-12', 25),
 ('instagram', '2021-12-09', 82),
 ('instagram', '2021-11-02', 75),
 ('instagram', '2021-10-21', 74),
 ('instagram', '2021-10-06', 50),
 ('instagram', '2021-10-03', 50),
 ('instagram', '2021-08-06', 12),
 ('instagram', '2021-08-02', 22),
 ('instagram', '2021-06-26', 12),
 ('instagram', '2021-05-20', 17),
 ('instagram', '2021-01-08', 14),
 ('instagram', '2021-05-16', 1),
 ('instagram', '2021-01-04', 10),
 ('instagram', '2021-01-17', 24),
 ('instagram', '2021-05-02', 32),
 ('instagram', '2021-02-16', 12),
 ('instagram', '2021-02-17', 23),
 ('instagram', '2021-03-31', 3),
 ('instagram', '2021-03-18', 12),
 ('instagram', '2021-03-08', 9),
 ('instagram', '2021-04-12', 3),
 ('instagram', '2021-02-06', 2),
 ('instagram', '2020-11-26', 12),
 ('instagram', '2022-01-13', 608),
 ('instagram', '2022-01-09', 230),
 ('instagram', '2022-01-02', 219),
 ('instagram', '2021-12-24', 36),
 ('instagram', '2021-12-11', 82),
 ('instagram', '2021-11-01', 74),
 ('instagram', '2021-10-24', 56),
 ('instagram', '2021-10-22', 70),
 ('instagram', '2021-10-18', 48),
 ('instagram', '2021-09-17', 46),
 ('instagram', '2021-06-15', 4),
 ('instagram', '2021-09-26', 44),
 ('instagram', '2021-09-14', 42),
 ('instagram', '2021-09-18', 32),
 ('instagram', '2021-09-03', 50),
 ('instagram', '2021-06-29', 265),
 ('instagram', '2021-07-04', 4),
 ('instagram', '2021-03-29', 5),
 ('instagram', '2020-11-22', 1),
 ('instagram', '2021-01-19', 16),
 ('instagram', '2021-06-04', 4),
 ('instagram', '2020-12-12', 2),
 ('instagram', '2021-03-19', 3),
 ('instagram', '2021-03-11', 13),
 ('instagram', '2021-03-05', 12),
 ('instagram', '2021-01-30', 4),
 ('instagram', '2021-01-28', 3),
 ('instagram', '2021-05-29', 1),
 ('instagram', '2022-01-30', 562),
 ('instagram', '2022-01-29', 608),
 ('instagram', '2021-11-21', 80),
 ('instagram', '2021-11-11', 90),
 ('instagram', '2021-10-01', 84),
 ('instagram', '2021-09-02', 40),
 ('instagram', '2020-12-01', 2),
 ('instagram', '2021-07-17', 30),
 ('instagram', '2021-07-06', 6),
 ('instagram', '2021-03-20', 92),
 ('instagram', '2021-08-04', 2),
 ('instagram', '2021-05-01', 53),
 ('instagram', '2021-04-20', 20),
 ('instagram', '2021-04-02', 6),
 ('instagram', '2021-04-05', 3),
 ('instagram', '2021-03-09', 6),
 ('instagram', '2021-03-10', 24),
 ('instagram', '2021-06-14', 6),
 ('instagram', '2021-05-08', 8),
 ('instagram', '2021-05-13', 17),
 ('instagram', '2021-08-12', 9),
 ('instagram', '2021-08-13', 8),
 ('instagram', '2021-07-26', 4),
 ('instagram', '2021-02-02', 4),
 ('instagram', '2021-01-26', 9),
 ('instagram', '2022-02-12', 1615),
 ('instagram', '2022-02-11', 3843),
 ('instagram', '2022-02-01', 3121),
 ('instagram', '2022-02-16', 570),
 ('instagram', '2022-01-24', 1439),
 ('instagram', '2022-01-06', 428),
 ('instagram', '2021-12-13', 59),
 ('instagram', '2021-10-30', 85),
 ('instagram', '2021-09-28', 80),
 ('instagram', '2021-09-15', 42),
 ('instagram', '2021-08-14', 10),
 ('instagram', '2021-07-19', 31),
 ('instagram', '2021-06-20', 5),
 ('instagram', '2021-06-01', 15),
 ('instagram', '2021-03-22', 50),
 ('instagram', '2021-07-08', 23),
 ('instagram', '2021-04-09', 33),
 ('instagram', '2021-01-15', 25),
 ('instagram', '2021-05-07', 4),
 ('instagram', '2021-05-04', 17),
 ('instagram', '2021-02-05', 11),
 ('instagram', '2021-04-08', 20),
 ('instagram', '2021-04-07', 19),
 ('instagram', '2021-06-09', 9),
 ('instagram', '2021-05-17', 4),
 ('instagram', '2021-04-18', 3),
 ('instagram', '2021-04-19', 3),
 ('instagram', '2020-11-21', 1),
 ('instagram', '2022-02-08', 2712),
 ('instagram', '2022-01-22', 814),
 ('instagram', '2021-12-27', 62),
 ('instagram', '2021-12-15', 107),
 ('instagram', '2021-12-06', 101),
 ('instagram', '2021-11-28', 129),
 ('instagram', '2021-11-07', 64),
 ('instagram', '2021-10-12', 91),
 ('instagram', '2021-09-07', 58),
 ('instagram', '2021-06-16', 8),
 ('instagram', '2021-01-07', 23),
 ('instagram', '2021-01-27', 17),
 ('instagram', '2021-01-06', 8),
 ('instagram', '2021-02-09', 23),
 ('instagram', '2021-05-05', 18),
 ('instagram', '2021-04-30', 91),
 ('instagram', '2021-01-14', 8),
 ('instagram', '2021-03-17', 15),
 ('instagram', '2021-03-16', 9),
 ('instagram', '2021-02-22', 5),
 ('instagram', '2021-02-27', 55),
 ('instagram', '2021-01-01', 3),
 ('instagram', '2022-01-15', 635),
 ('instagram', '2022-01-23', 701),
 ('instagram', '2021-12-08', 77),
 ('instagram', '2021-10-25', 72),
 ('instagram', '2021-10-11', 77),
 ('instagram', '2021-09-22', 52),
 ('instagram', '2021-08-07', 4),
 ('instagram', '2021-07-10', 11),
 ('instagram', '2021-06-25', 12),
 ('instagram', '2021-03-27', 10),
 ('instagram', '2021-07-07', 6),
 ('instagram', '2021-04-27', 33),
 ('instagram', '2021-04-22', 9),
 ('instagram', '2022-02-19', 82),
 ('instagram', '2021-02-10', 28),
 ('instagram', '2021-02-11', 10),
 ('instagram', '2021-02-25', 13),
 ('instagram', '2020-12-24', 6),
 ('instagram', '2021-04-21', 13),
 ('instagram', '2021-03-15', 8),
 ('instagram', '2021-03-06', 274),
 ('instagram', '2021-05-27', 4),
 ('instagram', '2021-08-27', 4),
 ('instagram', '2021-08-25', 8),
 ('instagram', '2021-08-19', 16),
 ('instagram', '2022-01-20', 1286),
 ('instagram', '2021-12-22', 58),
 ('instagram', '2021-09-27', 50),
 ('instagram', '2021-09-11', 26),
 ('instagram', '2021-09-04', 46),
 ('instagram', '2021-08-01', 4),
 ('instagram', '2021-07-27', 18),
 ('instagram', '2021-07-01', 61),
 ('instagram', '2021-06-19', 6),
 ('instagram', '2021-07-23', 13),
 ('instagram', '2021-08-22', 2),
 ('instagram', '2021-04-15', 16),
 ('instagram', '2020-12-18', 4),
 ('instagram', '2021-04-01', 16),
 ('instagram', '2021-03-01', 22),
 ('instagram', '2021-02-26', 104),
 ('instagram', '2021-08-30', 12),
 ('instagram', '2022-02-10', 2938),
 ('instagram', '2022-01-17', 1197),
 ('instagram', '2022-01-01', 372),
 ('instagram', '2021-12-30', 61),
 ('instagram', '2021-12-05', 34),
 ('instagram', '2021-11-26', 217),
 ('instagram', '2021-11-25', 355),
 ('instagram', '2021-11-16', 111),
 ('instagram', '2021-10-13', 54),
 ('instagram', '2021-10-08', 151),
 ('instagram', '2021-09-21', 36),
 ('instagram', '2021-09-08', 51),
 ('instagram', '2021-06-06', 1),
 ('instagram', '2021-05-11', 9),
 ('instagram', '2021-01-16', 85),
 ('instagram', '2021-02-28', 45),
 ('instagram', '2021-04-23', 6),
 ('instagram', '2022-02-09', 3934),
 ('instagram', '2022-01-25', 1098),
 ('instagram', '2022-01-11', 430),
 ('instagram', '2021-12-25', 32),
 ('instagram', '2021-12-17', 77),
 ('instagram', '2021-12-02', 109),
 ('instagram', '2021-11-27', 170),
 ('instagram', '2021-11-24', 311),
 ('instagram', '2021-11-22', 159),
 ('instagram', '2021-11-18', 112),
 ('instagram', '2021-11-13', 125),
 ('instagram', '2021-10-29', 74),
 ('instagram', '2021-11-06', 112),
 ('instagram', '2021-10-05', 52),
 ('instagram', '2021-06-21', 22),
 ('instagram', '2021-05-19', 24),
 ('instagram', '2021-04-03', 1),
 ('instagram', '2022-02-21', 30),
 ('instagram', '2021-08-21', 6),
 ('instagram', '2021-03-14', 60),
 ('instagram', '2021-04-13', 3),
 ('instagram', '2021-08-15', 8),
 ('instagram', '2021-08-26', 12),
 ('instagram', '2020-12-15', 3),
 ('instagram', '2022-01-16', 473),
 ('instagram', '2022-01-10', 456),
 ('instagram', '2021-12-07', 60),
 ('instagram', '2021-10-15', 70),
 ('instagram', '2021-09-30', 28),
 ('instagram', '2021-09-19', 34),
 ('instagram', '2021-09-05', 32),
 ('instagram', '2021-07-20', 31),
 ('instagram', '2021-07-05', 13),
 ('instagram', '2021-05-14', 2),
 ('instagram', '2021-03-13', 2),
 ('instagram', '2021-05-06', 41),
 ('instagram', '2021-08-28', 11),
 ('instagram', '2021-01-02', 3),
 ('instagram', '2021-04-17', 2),
 ('instagram', '2022-02-06', 1156),
 ('instagram', '2022-01-08', 211),
 ('instagram', '2021-12-31', 418),
 ('instagram', '2021-12-26', 16),
 ('instagram', '2021-12-21', 36),
 ('instagram', '2021-12-16', 80),
 ('instagram', '2021-12-01', 104),
 ('instagram', '2021-11-14', 75),
 ('instagram', '2021-11-08', 65),
 ('instagram', '2021-10-02', 50),
 ('instagram', '2021-09-09', 64),
 ('instagram', '2021-09-23', 65),
 ('instagram', '2021-07-21', 16),
 ('instagram', '2021-09-01', 30),
 ('instagram', '2021-03-25', 49),
 ('instagram', '2021-05-31', 11),
 ('instagram', '2021-03-21', 38),
 ('instagram', '2022-02-20', 50),
 ('instagram', '2021-02-12', 10),
 ('instagram', '2021-03-30', 4),
 ('instagram', '2021-08-09', 4),
 ('instagram', '2022-02-07', 2805),
 ('instagram', '2022-02-04', 3322),
 ('instagram', '2022-01-27', 1420),
 ('instagram', '2022-02-17', 295),
 ('instagram', '2021-12-19', 44),
 ('instagram', '2021-12-14', 80),
 ('instagram', '2021-12-03', 73),
 ('instagram', '2021-11-05', 84),
 ('instagram', '2021-10-14', 78),
 ('instagram', '2021-09-13', 50),
 ('instagram', '2021-08-31', 23),
 ('instagram', '2021-08-18', 4),
 ('instagram', '2021-06-08', 18),
 ('instagram', '2021-05-30', 4),
 ('instagram', '2021-07-03', 14),
 ('instagram', '2021-01-18', 28),
 ('instagram', '2021-01-10', 4),
 ('instagram', '2021-02-13', 55),
 ('instagram', '2021-03-07', 30),
 ('instagram', '2021-07-28', 5),
 ('instagram', '2021-02-07', 2),
 ('instagram', '2021-02-04', 4),
 ('instagram', '2021-01-25', 3),
 ('instagram', '2022-01-18', 993),
 ('instagram', '2022-01-31', 1641),
 ('instagram', '2021-12-28', 41),
 ('instagram', '2021-11-23', 207),
 ('instagram', '2021-11-19', 157),
 ('instagram', '2021-11-10', 133),
 ('instagram', '2021-03-23', 38),
 ('instagram', '2021-03-24', 23),
 ('instagram', '2021-07-12', 15),
 ('instagram', '2021-01-20', 8),
 ('instagram', '2021-03-12', 21),
 ('instagram', '2021-04-28', 20),
 ('instagram', '2021-01-31', 29),
 ('instagram', '2021-03-02', 65),
 ('instagram', '2021-03-03', 35),
 ('instagram', '2021-01-13', 21),
 ('instagram', '2020-12-10', 9),
 ('instagram', '2020-12-11', 2),
 ('instagram', '2021-08-16', 24),
 ('instagram', '2021-02-08', 4),
 ('instagram', '2021-01-05', 3),
 ('instagram', '2021-08-24', 17),
 ('instagram', '2022-01-14', 609),
 ('instagram', '2022-01-07', 331),
 ('instagram', '2021-12-20', 45),
 ('instagram', '2021-12-10', 88),
 ('instagram', '2021-12-04', 47),
 ('instagram', '2021-11-17', 188),
 ('instagram', '2021-10-31', 59),
 ('instagram', '2021-10-23', 35),
 ('instagram', '2021-10-20', 74),
 ('instagram', '2021-10-17', 26),
 ('instagram', '2021-09-29', 54),
 ('instagram', '2021-09-20', 40),
 ('instagram', '2021-07-14', 140),
 ('instagram', '2021-09-06', 30),
 ('instagram', '2021-07-18', 9),
 ('instagram', '2021-03-26', 104),
 ('instagram', '2021-05-12', 13),
 ('instagram', '2021-07-25', 11),
 ('instagram', '2022-02-18', 44),
 ('instagram', '2021-04-24', 13),
 ('instagram', '2020-12-23', 12),
 ('instagram', '2021-02-21', 7),
 ('instagram', '2021-01-21', 6),
 ('instagram', '2021-01-22', 1),
 ('youtube', '2021-10-11', 41),
 ('youtube', '2021-04-14', 68),
 ('youtube', '2021-05-23', 16),
 ('youtube', '2021-04-16', 22),
 ('youtube', '2021-04-17', 16),
 ('youtube', '2021-05-28', 12),
 ('youtube', '2021-04-22', 98),
 ('youtube', '2021-07-19', 15),
 ('youtube', '2021-04-19', 5),
 ('youtube', '2021-07-22', 10),
 ('youtube', '2021-06-27', 10),
 ('youtube', '2021-06-23', 12),
 ('youtube', '2021-06-01', 12),
 ('youtube', '2021-04-23', 62),
 ('youtube', '2021-07-08', 6),
 ('youtube', '2021-06-05', 7),
 ('youtube', '2021-04-27', 38),
 ('youtube', '2022-01-17', 3),
 ('youtube', '2022-02-10', 2),
 ('youtube', '2022-01-24', 8),
 ('youtube', '2021-07-03', 6),
 ('youtube', '2021-10-23', 1),
 ('youtube', '2021-10-13', 4),
 ('youtube', '2022-01-15', 1),
 ('youtube', '2021-07-14', 2),
 ('youtube', '2021-05-30', 4),
 ('youtube', '2021-05-25', 2),
 ('youtube', '2022-02-02', 1),
 ('youtube', '2021-12-30', 1),
 ('youtube', '2021-12-05', 2),
 ('youtube', '2021-05-03', 27),
 ('youtube', '2021-12-03', 2),
 ('youtube', '2021-11-01', 3),
 ('youtube', '2021-10-25', 1),
 ('youtube', '2021-02-13', 1),
 ('youtube', '2021-01-18', 2),
 ('youtube', '2021-09-20', 1),
 ('youtube', '2021-09-13', 1),
 ('youtube', '2021-03-29', 2),
 ('youtube', '2021-03-22', 1),
 ('youtube', '2021-03-15', 1),
 ('youtube', '2022-01-09', 1),
 ('youtube', '2021-10-26', 8),
 ('youtube', '2021-05-24', 15),
 ('youtube', '2021-10-12', 11),
 ('youtube', '2021-05-31', 30),
 ('youtube', '2021-04-20', 622),
 ('youtube', '2021-06-14', 11),
 ('youtube', '2021-05-01', 8),
 ('youtube', '2021-04-30', 12),
 ('youtube', '2021-04-28', 34),
 ('youtube', '2021-02-26', 15),
 ('youtube', '2021-02-27', 20),
 ('youtube', '2021-07-01', 7),
 ('youtube', '2021-06-18', 2),
 ('youtube', '2021-06-16', 18),
 ('youtube', '2021-12-28', 5),
 ('youtube', '2022-01-21', 3),
 ('youtube', '2021-06-21', 9),
 ('youtube', '2021-06-13', 20),
 ('youtube', '2021-11-19', 241),
 ('youtube', '2021-12-01', 6),
 ('youtube', '2021-11-21', 20),
 ('youtube', '2021-11-09', 1),
 ('youtube', '2021-05-26', 2),
 ('youtube', '2022-02-03', 1),
 ('youtube', '2021-12-26', 2),
 ('youtube', '2021-12-27', 4),
 ('youtube', '2021-12-06', 2),
 ('youtube', '2021-10-01', 3),
 ('youtube', '2021-07-30', 2),
 ('youtube', '2021-02-19', 1),
 ('youtube', '2021-02-02', 1),
 ('youtube', '2021-01-27', 1),
 ('youtube', '2021-01-13', 1),
 ('youtube', '2021-08-29', 1),
 ('youtube', '2021-08-09', 1),
 ('youtube', '2021-10-08', 350),
 ('youtube', '2021-05-14', 30),
 ('youtube', '2021-05-12', 19),
 ('youtube', '2021-07-20', 15),
 ('youtube', '2021-10-18', 15),
 ('youtube', '2021-10-17', 13),
 ('youtube', '2021-06-04', 16),
 ('youtube', '2021-06-17', 16),
 ('youtube', '2021-05-11', 36),
 ('youtube', '2021-04-24', 60),
 ('youtube', '2021-02-23', 2),
 ('youtube', '2021-02-25', 24),
 ('youtube', '2021-06-22', 4),
 ('youtube', '2021-06-02', 20),
 ('youtube', '2021-12-08', 49),
 ('youtube', '2022-01-23', 10),
 ('youtube', '2021-06-30', 18),
 ('youtube', '2021-06-29', 10),
 ('youtube', '2021-06-15', 4),
 ('youtube', '2021-04-18', 4),
 ('youtube', '2021-05-07', 14),
 ('youtube', '2021-06-28', 7),
 ('youtube', '2021-12-11', 7),
 ('youtube', '2021-10-24', 1),
 ('youtube', '2021-12-13', 3),
 ('youtube', '2022-01-10', 2),
 ('youtube', '2021-11-17', 7),
 ('youtube', '2021-11-16', 12),

## Export

In [8]:
df = RDD.toDF(['social_media', 'date', 'count'])
df.show()

+------------+----------+-----+
|social_media|      date|count|
+------------+----------+-----+
|   instagram|2022-01-12|  439|
|   instagram|2022-01-26| 1235|
|   instagram|2022-01-19| 1357|
|   instagram|2022-01-04|  446|
|   instagram|2021-11-20|  150|
|   instagram|2021-11-12|  148|
|   instagram|2021-11-09|   65|
|   instagram|2021-11-03|   96|
|   instagram|2021-10-26|   44|
|   instagram|2021-10-19|   65|
|   instagram|2021-10-07|   38|
|   instagram|2021-08-05|    6|
|   instagram|2021-07-16|  110|
|   instagram|2021-06-24|   13|
|   instagram|2021-07-13|   10|
|   instagram|2021-04-11|    9|
|   instagram|2021-02-24|   21|
|   instagram|2021-02-18|   17|
|   instagram|2021-07-30|   14|
|   instagram|2021-08-20|    4|
+------------+----------+-----+
only showing top 20 rows

In [10]:
df.write.csv(out_url)

Py4JJavaError: An error occurred while calling o310.csv.
: org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:198)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:159)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:696)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:696)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:696)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:305)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:291)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)
	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:684)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 35 in stage 58.0 failed 1 times, most recent failure: Lost task 35.0 in stage 58.0 (TID 1584, localhost, executor driver): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:257)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: Input row doesn't have expected number of values required by the schema. 3 fields are required while 2 values are provided.
	at org.apache.spark.sql.execution.python.EvaluatePython$$anonfun$makeFromJava$15$$anonfun$apply$15.applyOrElse(EvaluatePython.scala:184)
	at org.apache.spark.sql.execution.python.EvaluatePython$.org$apache$spark$sql$execution$python$EvaluatePython$$nullSafeConvert(EvaluatePython.scala:208)
	at org.apache.spark.sql.execution.python.EvaluatePython$$anonfun$makeFromJava$15.apply(EvaluatePython.scala:180)
	at org.apache.spark.sql.SparkSession$$anonfun$6$$anonfun$apply$5.apply(SparkSession.scala:752)
	at org.apache.spark.sql.SparkSession$$anonfun$6$$anonfun$apply$5.apply(SparkSession.scala:752)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:245)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:242)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:248)
	... 10 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1925)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1913)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1912)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1912)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:948)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:948)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:948)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2146)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2095)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2084)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:759)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:167)
	... 33 more
Caused by: org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:257)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IllegalStateException: Input row doesn't have expected number of values required by the schema. 3 fields are required while 2 values are provided.
	at org.apache.spark.sql.execution.python.EvaluatePython$$anonfun$makeFromJava$15$$anonfun$apply$15.applyOrElse(EvaluatePython.scala:184)
	at org.apache.spark.sql.execution.python.EvaluatePython$.org$apache$spark$sql$execution$python$EvaluatePython$$nullSafeConvert(EvaluatePython.scala:208)
	at org.apache.spark.sql.execution.python.EvaluatePython$$anonfun$makeFromJava$15.apply(EvaluatePython.scala:180)
	at org.apache.spark.sql.SparkSession$$anonfun$6$$anonfun$apply$5.apply(SparkSession.scala:752)
	at org.apache.spark.sql.SparkSession$$anonfun$6$$anonfun$apply$5.apply(SparkSession.scala:752)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:245)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:242)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:248)
	... 10 more